name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force "https://lp33:${HF_TOKEN}@huggingface.co/spaces/lp33/furniture-detection"

